### PR TITLE
fix: generate source maps using `sass` with asset/resource

### PR DESCRIPTION
**Pull request by xoxys**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Supersedes: https://github.com/webpack-contrib/sass-loader/pull/968
Fixes: https://github.com/webpack-contrib/sass-loader/issues/962

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by xoxys** [comment]
@alexander-akait How to handle the CLA? I mean, the commit was not done by me...

**Comment by alexander-akait** [comment]
You should not use another person PR, just send the same, CLA was assign by `Alexey Lavinsky` so you have right to copy code

**Comment by xoxys** [comment]
Why is my mailing address required to for the CLA? IMO a bit too much data that is requested.

**Comment by alexander-akait** [comment]
We use email from commits

**Comment by xoxys** [comment]
No Im talking about my postal address. The docusign document that need to be signed during the CLA process is asking for my private mailing/postal address...

**Comment by alexander-akait** [comment]
Very strange, it never asks it before, are you assign as `Individual Contributor`?

**Comment by xoxys** [comment]
Yes as an individual contributor:
image

**Comment by alexander-akait** [comment]
Just use the same email as you use in commit

**Comment by xoxys** [comment]
It is not the email address, there is a dedicated field for it, not shown in the screenshot. However, I've added `private` to the two lines now, hope that works for you

**Comment by xoxys** [comment]
How to proceed? Workflows need approvals I guess.

**Comment by xoxys** [comment]
@alexander-akait looks like it needs another approval

**Comment by alexander-akait** [comment]
There is interesting situation around https://github.com/webpack-contrib/sass-loader/issues/774, new compiler API fully remove all related source map options (i.e. only `sourceMap: true`) exists, so looking ahead I think we need to revisit something here, I think we should allow to generate custom `sourceMappingURL`, otherwise the current solution will not be compatible with modern sass API. Any ideas?

**Comment by xoxys** [comment]
I think this goes a bit beyond my knowledge about how all works together :(

**Comment by alexander-akait** [comment]
yep, hard to find better solution here, only developer know location, maybe we should allow to modify CSS from Sass...

**Pull request closed without merging**
