### PR TITLE
fix(loader): source map `sources` and `file` paths

### PR DESCRIPTION
**Pull request by npetruzzelli**
-   Improves source map path reliability (legacy and normal)
-   Fix `sources` and `file` to be URLs that are relative to the file containing the map.
    -   Because of how dramatically different this is, the user must opt-in to this part of the fix by setting `legacySourceMaps` option to `false`. Making this fix the default behavior would be a breaking change requiring a new major version.

**Side note:** `npm run test-source-map` throws an error when using webpack 4.5+. I needed to install webpack 3.x for it to run correctly.

This contributes to the fixes for
-   https://github.com/webpack-contrib/sass-loader/issues/529
-   https://github.com/webpack-contrib/css-loader/issues/652

### CODE REVIEW

**Comment by npetruzzelli** [comment]
See also: https://github.com/webpack-contrib/css-loader/pull/753

**Comment by npetruzzelli** [comment]
I'm seeing some build errors that I did not experience locally. I'll have to look have another look.

**Comment by npetruzzelli** [comment]
Looks like:
-   I need to update an existing test
-   I need to add additional tests

**Comment by npetruzzelli** [comment]
Before fix:
image

After fix (including css-loader fix): 
image

**Comment by evilebottnawi** [comment]
Also you PR is breaking change, we can't accept this

**Comment by npetruzzelli** [comment]
@evilebottnawi - I've removed the option part of it. I still need to update the test suite and create a test repo. It may take me some time to get to it. I'll comment again once it is all in place. You may see commits trickle in in the mean time.

I believe concerns about it being a breaking change may be addressed by then, if not, I may have more questions at that time.

**Comment by evilebottnawi** [comment]
Close due inactivity, if you still have problem please open issue, sorry for delay

**Pull request closed without merging**
