### PR TITLE
add string support to importer param

### PR DESCRIPTION
**Pull request by serheyShmyg**
Hi, let's make importer param available as string, mean importer === path to file with handler.

### CODE REVIEW

**Comment by serheyShmyg** [comment]
node-sass cli describe --importer as path to js file with handler.
And also it's query string support.

**Comment by evilebottnawi** [comment]
@serheyShmyg can your provide link on documentation about this, but need tests for this anyway

**Comment by serheyShmyg** [comment]
https://github.com/sass/node-sass#command-line-interface
I'll add tests

**Comment by evilebottnawi** [comment]
@serheyShmyg we use programmatic api, not CLI, your can just use `require('path/to/importer')` without changed `sass-loader` code.

**Comment by serheyShmyg** [comment]
it wouldn't work with query string options.

**Comment by evilebottnawi** [comment]
@serheyShmyg what query string? Please provide full example (case), it is difficult to understand

**Pull request closed without merging**
