### PR TITLE
feat(importer): add support for custom file extensions (`options.extensions`)

### PR DESCRIPTION
**Pull request by benembery**
We are looking to add custom extensions support. Enabling files to be swapped out at compile time.

The following example allows shows the how the extensions would be configured.

```js
{
  loader: "sass-loader",
    options: {
      sourceMap: true,
      extensions: [`.myext.scss`, ".scss", ".sass", ".css"],
    }
}
```

In our use case, we supply an arg to webpack-cli that configures the custom extension we wish to build. 

Would you be interested in adding this to sass-loader as a feature.

### CODE REVIEW

**Comment by jhnns** [comment]
The change seems ok and I'm kind of surprised that the tests still work, because the resolving logic is very brittle and did break the build several times.

However, I need to think about this change because I want to simplify the resolving behavior. Can you elaborate on your use case a little bit? Why would you want to deviate from Sass' default resolving behavior?

Maybe, this change also needs to be aligned with https://github.com/webpack-contrib/sass-loader/pull/573

**Comment by benembery** [comment]
Hi @jhnns,
Thanks for taking a look at this.

Our use is multi-tenant web applications, where we wish to build from the same source but with specific modifications per tenant. 
For example, I would create a master file, colours.scss and have a tenant-specific version named colours.tenant.scss and would like that to be picked up by sass when I am compiling with that tenant.

We are currently doing this for js files with webpack using `resolve:extensions` in the webpack configuration.

If you need more information than this, let me know.

**Comment by evilebottnawi** [comment]
You can do this using:
```
{
  test: /\.scss$/,
  loader: "sass-loader",
  resolve: {
    extensions: [ 'my', 'custom', 'extensions', 'scss', 'sass', 'css']
  }
},
```

**Comment by benembery** [comment]
Hi, I'm very sorry for the delay getting you an example.
https://github.com/benembery/multi-tenant-sass-example 
If you need anymore information let me know.

**Pull request closed without merging**
