### PR TITLE
fix: resolving of scoped npm packages

### LINKED ISSUE #424: Resolving `@import` to scoped npm packages
As continue of issue #382 there is a problem in `sass-loader` or `webpack` with resolving `.scss` files in
scoped npm packages (`node_modules/@org/pkg`) if there no explicit importing path, sass-loader will
not recognize package in `node_modules` and throw `File to import not found or unreadable: ...` error. Also, to note there is no error when using simply `css-loader` to resolve `.css` files.
See example: https://github.com/vanesyan/webpack-npm-scope-css-import-issue

### PR DESCRIPTION
**Pull request by vanesyan**
Fix #424

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@vanesyan thanks :+1:

**Comment by vanesyan** [comment]
Any updates on the thread?

**Comment by sirlancelot** [comment]
Any chance someone could get this merged? This is actually going to be a growing issue as more people start trying to bundle `material-components-web` which uses scoped packages extensively.

@sokra

**Comment by michael-ciniawsky** [comment]
@bebraw @d3viant0ne Does one of you have acces here? 😛  It's seems @jhnns is busy atm

**Comment by d3viant0ne** [comment]
@sirlancelot - contrib was created to allow Tobias and other core member focus on Webpack. If you need to get a hold of someone, try the lead maintainer ( for repos like sass-loader that have one )

For other libs in `webpack-contrib` that are maintained by the organization or if you can't get in contact with the lead maintainer ( real life happens ) tag `@webpack-contrib/org-maintainers ` or `@d3viant0ne @bebraw`.

If none of that works, DM me on gitter or twitter.

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - I'm working on that now, i'll get this sorted shortly.

**Comment by sirlancelot** [comment]
Thanks @d3viant0ne, I hadn't realized others were maintaining this. Thanks so much for you contributions!

**Comment by vanesyan** [comment]
Can you also, please, upstream fix on npm?! :)

**Comment by merofeev** [comment]
Hello @d3viant0ne, @bebraw, @vanesyan!
This seems to be breaking [recommended way](https://material.angular.io/guide/theming#defining-a-custom-theme) to import custom Angular Material theme (at least for me).

This worked fine with sass-loader 6.0.3
`@import '~@angular/material/theming';` 
With sass-loader 6.0.4 this import leads to error:
`File to import not found or unreadable: ~@angular/material/theming.`

To make it work with sass-loader 6.0.4 I had to write
`@import "~@angular/material/_theming.scss";`

**Comment by vanesyan** [comment]
Yes, it seems that with landed pr sass-loader preventing from processing file formatting, (e.g. adding underscore and file extension on lines [42-47](https://github.com/vanesyan/sass-loader/blob/master/lib/importsToResolve.js#L42-L47)

**Comment by pselden** [comment]
Also breaking my build.

**Pull request merged**
