### PR TITLE
fix: wrong file extension resolution from webpack

### LINKED ISSUE #804: SassError: Can't find stylesheet to import when it contains @forward with _index file
- Operating System: Mac OS
- Node Version: v10.16.3
- NPM Version: v6.13.4
- webpack Version: v4.41.5
- sass-loader Version: v8.0.2
- dart-sass version: v1.25.0

### Expected Behavior

Expected `sass-loader` to resolve the module when `_index.scss` files are used.

### Actual Behavior

`sass-loader` throws following error when `@import`'ed Sass file contain `@forward` statement with _index file. (See reproducible steps below).

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
```

### Code

See complete example here:
https://github.com/abhiomkar/sass-module-bug

### How Do We Reproduce?

```
git clone git@github.com:abhiomkar/sass-module-bug.git
cd sass-module-bug
npm i
npx webpack
```

Notice the error:

```
[./fixture-import.scss] 434 bytes {main} [built] [failed] [1 error]

ERROR in ./fixture-import.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @forward "@material/base" as mdc-base-*;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/@material/button/_mixins.import.scss 1:1  @import
  /Users/abhiomkar/code/sass-bug-module/fixture-import.scss 1:9 
```

Changing webpack entry file `fixture-import.scss` => `fixture-use.scss` would fix the error.

UPDATE: See [this comment](https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020) for temporary workaround.

### PR DESCRIPTION
**Pull request by itsUndefined**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
Closes #804 and makes google material usable again.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Unfortunately it is breaking change, but yes we should fix it, it is already in my TODO, I am afraid we need other logic because tests are broken

**Comment by itsUndefined** [comment]
Sadly you are correct. I wanted to make the PR just in case it was that easy. Sorry I didn't try to run the tests locally. If it helps, the libraries that are broken only have a main field with a javascript file instead of a sass or css field inside the package.json

**Comment by evilebottnawi** [comment]
@itsUndefined I will look at this tomorrow, top in my TODO, maybe it is time to breaking change

**Comment by itsUndefined** [comment]
So many projects are blocked because of this issue. A lot of them do not have ejected the webpack configuration to switch the webpackImporter to false. Maybe set webpackImporter to false as the default and deploy a new version to fix those projects while you search for a better solution?

**Comment by evilebottnawi** [comment]
@itsUndefined No, it is a breaking change and breaks more projects

**Comment by evilebottnawi** [comment]
Looks like won't fix https://github.com/webpack-contrib/sass-loader/issues/804

**Pull request closed without merging**
