### PR TITLE
feat: optimize debug message formatting, #1065

### PR DESCRIPTION
**Pull request by webdiscus**
docs: add impofration how to enable @debug output

This PR contains a:

- [ ] **bugfix**
- [x ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

1. The debug message on each line is too long because the output contains an absolute file before self message.
    Here was changed debug message formatting to:  [debug:line:column] message.
2. In readme is added "How to enable @debug output", because since sass-loader 1.12.0 the output of `@debug` is disabled  by default.
 
 Details see in the [issue](https://github.com/webpack-contrib/sass-loader/issues/1065).

### Breaking Changes

NO

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Comment by webdiscus** [comment]
@alexander-akait 

in my last commit [test: change expected values in snap for optimized @debug output](https://github.com/webpack-contrib/sass-loader/pull/1066/commits/a7308020e3ff051acedc28ec9971c1825edd8284) are fixed test snaps, now all test are passed.

**Comment by alexander-akait** [comment]
Can you fix an error error?

**Comment by webdiscus** [comment]
> Can you fix an error error?

This is not code error, this is Lint error:

```
[lint:prettier] src/utils.js
ERROR: "lint:prettier" exited with 1.
Error: Process completed with exit code 1.
```
It was already in master before I cloned it.

I try to find the error.  I can reproduce this issue by me local with `npm run lint`

**Comment by alexander-akait** [comment]
Yes, can you fix it?

**Comment by webdiscus** [comment]
> Yes, can you fix it?

Yes, I can. I found the place in source. The lint has very strange rules.

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
