### PR TITLE
fix: backported disabled auto importing `fiber` on node >= 16

### PR DESCRIPTION
**Pull request by Morgul**
Original Changes: 4ca004b

This PR contains a:

- [X] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [X] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Backported the changes from 4ca004b to the 10.x line, so that projects stuck on Webpack 4 can still use Node v16.

### Additional Info

There are unit test failures that seem unrelated to these changes, and the unit tests wouldn't run at all for me before them, so I'm unsure how to handle them.

Additionally, I'm not sure if the `v10` branch is the correct one, let me know if this needs to be against a different branch.

### CODE REVIEW

**Comment by alexander-akait** [comment]
Can you accept CLA?

**Comment by Morgul** [comment]
> Can you accept CLA?

Well, I've now filled it out twice, and it doesn't seem to have updated... I'm not sure what I'm missing?

**Comment by Morgul** [comment]
Turns out I had to just rewrite the author on the commit, and now it seems all good.

**Comment by alexander-akait** [comment]
Thanks

**Comment by alexander-akait** [comment]
Released, try `10.2.1`

**Comment by Morgul** [comment]
It works perfectly!

**Comment by mariadb-ThienLy** [comment]
For some reason, we can only stick with v8.
Would it be possible to merge this to v8 then make a release for `8.0.3`?
Thanks

**Pull request merged**
