### PR TITLE
feat: replace clone-deep with Lodash version 

### PR DESCRIPTION
**Pull request by kevinji**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [X] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

This uses the Lodash `_.cloneDeep` function instead of a separate `clone-deep` package in order to cut down on unnecessary deps.

### Breaking Changes

N/A

### Additional Info

N/A

### CODE REVIEW

**Comment by kevinji** [comment]
Is there any significant difference between that library (which doesn't seem to do exactly the same thing) and Lodash in terms of features / performance?

**Comment by evilebottnawi** [comment]
@kevinji it is very popular library and is very stable

**Comment by kevinji** [comment]
I don't think it quite does the same thing; the relevant line of code is

https://github.com/webpack-contrib/sass-loader/blob/eac8160f3f45c37733c7663641c204bcbe88f858/lib/normalizeOptions.js#L23

which doesn't have to merge two objects; it just needs to clone a single one.

Lodash is also [very popular](https://www.npmjs.com/package/lodash) so I figured that it would be a good choice.

**Comment by kevinji** [comment]
Hmm, what about using the regular `lodash` package and then using the imports under that?

**Comment by evilebottnawi** [comment]
@kevinji don't think we need `lodash` only for one purpose, what is problem with using currently package?

**Comment by kevinji** [comment]
I was hoping to cut down on the number of transitive dependencies; `clone-deep` introduces more dependencies, which means more possible repos that could possibly be hijacked.

**Comment by evilebottnawi** [comment]
@kevinji sorry but we can't do here, adding outdated package is bad idea, current using package is very small

**Pull request closed without merging**
