### PR TITLE
feat: add dart-sass support default

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@xiaoxiangmoe Why we should switch on `dart-sass` right now?

**Comment by xiaoxiangmoe** [comment]
@evilebottnawi  

This code will use node-sass as the default implementation.

Dart-sass is used when node-sass is missing and dart sass is installed. So there are no destructive updates.

https://sass-lang.com/dart-sass

> Dart Sass is the primary implementation of Sass, which means it gets new features before any other implementation.

**Comment by xiaoxiangmoe** [comment]
It isn't breaking change. It will still use node-sass if there exists node-sass without any config.

**Comment by xiaoxiangmoe** [comment]
Okay. @evilebottnawi Could you please tell me the plan for the release of the next major version? Thanks.

**Comment by evilebottnawi** [comment]
fir problem https://github.com/webpack-contrib/sass-loader/issues/556#issuecomment-437641222 and `mainField` for current release and we can start new major release

**Comment by sibiraj-s** [comment]
If that is going in a next major version then there is no need for fallback. We can just reverse whatever we do now..

from
```
const render = getRenderFuncFromSassImpl(options.implementation || require("node-sass"));
```

to 

```
const render = getRenderFuncFromSassImpl(options.implementation || require("sass"));
```

rite? It will be breaking however @xiaoxiangmoe @evilebottnawi

**Comment by evilebottnawi** [comment]
@sibiraj-s what do you mean?

**Comment by sibiraj-s** [comment]
Hi @evilebottnawi .

Here for new installations `dart-sass` is considered/recommended as default instead of `node-sass`. A check is added to avoid breaking change for those who upgrade with node-sass installed.

You said that this PR will go in the next major release(considering `8.0.0`). In that case, these fallback strategies implemented in this PR is not needed, since major release are expected to have breaking change. User can uninstall `node-sass` and install `sass` and start using it or add the `implementation` method to retain the functionality.

We can just reverse the existing method. Instead of looking for `node-sass`, now we require `sass`. No need for try/catch or anything.

**Comment by evilebottnawi** [comment]
WIP on this, will be released in `sass-loader@7.2.0`

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/sass-loader/pull/646, will be released in `7.2.0`, anyway thanks for work and idea :+1:

**Comment by xiaoxiangmoe** [comment]
@evilebottnawi When will `7.2.0` be released?

**Comment by evilebottnawi** [comment]
@xiaoxiangmoe when it is ready for release, already in my todo list, ETA around 1-2 weeks

**Comment by xiaoxiangmoe** [comment]
@evilebottnawi Excuse me, what does ETA mean?

**Comment by evilebottnawi** [comment]
@xiaoxiangmoe many work, this month, sorry

**Comment by xiaoxiangmoe** [comment]
@evilebottnawi Thank you very much. 
By the way, I still want to know whether ETA is the abbreviation for `estimated time of arrival` or something else.

**Comment by xiaoxiangmoe** [comment]
@evilebottnawi Excuse me. Do you need any help?

**Comment by evilebottnawi** [comment]
@xiaoxiangmoe migrate test on jest and snapshoting

**Comment by xiaoxiangmoe** [comment]
@evilebottnawi I am happy to help. Can you give me some guidance? Do I need to upgrade jest to the latest version and update snapshoting?

**Pull request closed without merging**
