### PR TITLE
docs: rename `dart-sass` to `sass`

### PR DESCRIPTION
**Pull request by evilebottnawi**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Dart sass have `sass` name in `npm` repository (https://github.com/sass/dart-sass/blob/master/package/package.json#L2)

**Comment by evilebottnawi** [comment]
Feel free to feedback

**Comment by suazithustra** [comment]
My `sass` module isn't being resolved, i'm getting the `Cannot find module 'node-sass'` error.

**Comment by evilebottnawi** [comment]
@suazithustra run `npm i node-sass --save-dev` or `npm i sass --save-dev` (`dart-sass`)

**Comment by suazithustra** [comment]
I did `yarn add -D sass`. It's not being resolved.

**Pull request merged**
