### PR TITLE
test: sass modules "@use"

### PR DESCRIPTION
**Pull request by donnysim**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Sass launched modules feature not too long ago and its path resolution works the same way as `@import` does, no changes are required to support it. There are slight differences for `@use` vs `@import` when testing:

- All `@use` are resolved only once no matter how many times the same file is included;
- Requires quotes in scss and sass;
- Imports like `~bootstrap` require alias - `@use "~bootstrap" as bootstrap` because `~bootstrap` is invalid name in sass;
- Does not support `@use url` - that's `@import` responsibility;
- Does not support multiple `@use` in one line separated by comma - each `@use` must be on new line;
- Does not support css nesting like `.class { @import "path" }`;

At the moment only Dart Sass 1.23.0 and up support `@use` feature so bumped sass dependency.

### Breaking Changes

None.

### Additional Info

http://sass.logdown.com/posts/7858341-the-module-system-is-launched

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Big thanks!

**Comment by egze** [comment]
Sorry, does it mean I can use `@use` if I install the latest `sass-loader`?

**Comment by donnysim** [comment]
@egze only thing you need is to install `sass` v1.23 or later to use it and make sure you don't have `node-sass` dependency (it doesn't support `@use` yet, or keep both but configure `sass-loader` to use `sass`). No changes are needed for `sass-loader` to support it as it uses the same path resolution implementation as `@import`.

**Comment by mitinarseny** [comment]
When using dart sass, `@use '~some_thing/another'` do not resolve `~`. Any help?

**Comment by donnysim** [comment]
@mitinarseny I tested it and it does resolve it - things like `@use "~bootstrap/scss/function"` all work without any problems. If your import is something like `@use "~bootstrap"` then you *must* add `as some-name` as in `@use "~bootstrap" as bootstrap` etc. because it cannot create a module variable named `~bootstrap`.
If  you have some other problem, would be nice to have more info.

**Comment by mitinarseny** [comment]
@donnysim Error is here:
```
```


```js
// webpack.config.js


```


```

**Comment by mitinarseny** [comment]
@donnysim Sure:
```
ERROR in ./src/sass/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??ref--5-2!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/sass/main.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @use '~katex/dist/katex.css';
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/sass/base/_typography.scss 1:1  @use
  src/sass/base/_index.scss 2:1       @use
  /Users/mitinarseny/dev/hse/statistics/hw_new/src/sass/main.scss 4:1                           root stylesheet
 @ ./src/sass/main.scss 1:14-190 20:4-31:5 23:25-201
 @ ./src/main.js
```
```js
// in main.js

import './sass/main.scss';
```
```bash
$ tree sass
sass
├── abstracts
│   ├── _index.scss
│   └── _variables.scss
├── base
│   ├── _index.scss
│   ├── _reset.scss
│   └── _typography.scss
├── layout
│   ├── _grid.scss
│   └── _index.scss
└── main.scss
```
```scss
// sass/main.scss

@charset 'utf-8';

@use 'abstracts';
@use 'base';
@use 'layout';
```
```scss
// sass/base/_index.scss

@import 'reset';
@import 'typography';
```
```scss
// sass/base/_typography.scss

@use '~katex/dist/katex.css';
@use '~firacode/distr/fira_code.css';
```
```js
// in webpack.config.js

{
  test: /\.s[ac]ss$/i,
  use: [
    'style-loader',
    'css-loader',
    {
      loader: 'postcss-loader', // Run postcss actions
      options: {
        plugins: function () { // postcss plugins, can be exported to postcss.config.js
          return [
            require('autoprefixer')
          ];
        }
      }
    },
    {
      loader: 'sass-loader',
      options: {
        // Prefer `dart-sass`
        implementation: require('sass'),
        sassOptions: {
          fiber: require('fibers'),
        },
      },
    },
  ],
}
```

**Comment by donnysim** [comment]
@mitinarseny you could try removing the .css extension - `@use "~katex/dist/katex"` and it should find it. If it's a bug or not, I'm not sure. Though you'll most likely need to add `resolve-url-loader` because webpack resolves assets based on original source file so it won't find any assets inside the css file etc..

**Comment by mitinarseny** [comment]
> you could try removing the .css extension - `@use "~katex/dist/katex"` and it should find it

Nope. It does not have any influence, it's just a recommendation according to sass docs. Anyway, this is solution which I came to, too:
> In addition, you'll most likely need to add resolve-url-loader because webpack resolves assets based on original source file so it won't find any assets inside the css file etc..

And it works, but you should remove `~` and import like:
```scss
import 'katex/dist/katex';
```

BTW, `@use` should not use `url()`, according to sass docs.

**Comment by dietergeerts** [comment]
I'm currently investigating to start using "@use", and I wonder if it works if you have multiple `scss` imports from `js` files? So for example, I know solve the "output styling rules only once, even if shared across components" like this :

component-a.js
```
import './component-base.js';
import './component-a.scss';
```

component-b.js
```
import './component-base.js';
import './component-b.scss';
```

component-base.js
```
import './component-base.scss';
```

And because of this, the styling inside the "base" sass file will be included only once, and in the correct order (this is how I have been doing sass modules for quite some while, and it works so great for only having the things used in your bundle). If I would add this as an import in the individual sass files for the components, someone that imports both components will end up with duplicate styling rules in the result. 

I saw '@use', and I wonder if this could remove this extra `js` wrapper file for the "base" styling in my example? Because the sass-loader triggers for each separate `scss` import, I expect this not being the case, but I could be wrong.

**Pull request merged**
